#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
# -f src/build.xml
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}

mkdir -p build

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi
    mvn clean $MAVEN_INST_DEPLOY -DskipTests -Psources -Pjavadoc -Phadoop-2 -fae "$@"

    if [ -z "${MAVEN_ONLY}" ]; then
        (cd packaging; mvn package -Pdist)
        mkdir -p build/hive-${FULL_VERSION}
        tar --strip-components 1 -C build/hive-${FULL_VERSION} -xf packaging/target/apache-hive*bin.tar.gz
        mkdir -p build/hive-${FULL_VERSION}/docs
        mkdir -p build/hive-${FULL_VERSION}/data/scripts
        cp -r docs/* build/hive-${FULL_VERSION}/docs
        cp data/scripts/q_test_*.sql build/hive-${FULL_VERSION}/data/scripts
        (cd build && tar --exclude='*/native/lib*' --exclude='*/lib/native/*' -czf hive-${FULL_VERSION}.tar.gz hive-${FULL_VERSION})
    fi
else
    git add .
    git commit -a -m "Temporary commit for tarball"
    git archive --prefix=hive-${FULL_VERSION}/ --format=tar HEAD |gzip > build/hive-${FULL_VERSION}.tar.gz
fi
