#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
# -f src/build.xml
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}

if [ ! -e build ]; then
    if [ ! -e src/build ]; then
        mkdir src/build
    fi
    ln -s -f src/build .
fi

if [ -f cloudera/build.properties ]; then
    cp -r cloudera/* src/cloudera
fi

if [ -z "$GIT_REPO" ]; then
    cd src

    ant -Dhadoop.security.version.prefix=0.23 \
        -Dreactor.repo=file://${HOME}/.m2/repository -Divy.home=${HOME}/.ivy2 -Dmvnrepo=$IVY_MIRROR_PROP \
        -propertyfile cdh.build.properties -Dinclude.postgres=true tar "$@"
    
# Change to cloudera/maven directory, and install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
    cd cloudera/maven-packaging
    mvn -Dnot.cdh.release.build=false -Dmaven.repo.local=${HOME}/.m2/repository  install $DO_MAVEN_DEPLOY
else
    (cd src; mvn -f cloudera-pom.xml process-resources)
    git add .
    git commit -a -m "Temporary commit for tarball"
    git archive --prefix=hive-${FULL_VERSION}/ --format=tar HEAD |gzip > build/hive-${FULL_VERSION}.tar.gz
fi