#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
# -f src/build.xml
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}

if [ ! -e build ]; then
    ln -s -f src/build .
fi

if [ -f cloudera/build.properties ]; then
    cp -r cloudera/* src/cloudera
fi

cd src

ant -Dhadoop.security.version.prefix=0.23 \
    -Dreactor.repo=file://${HOME}/.m2/repository -Divy.home=${HOME}/.ivy2 -Dmvnrepo=$IVY_MIRROR_PROP \
    -propertyfile cdh.build.properties -Dinclude.postgres=true tar "$@"

# Change to cloudera/maven directory, and install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
cd cloudera/maven-packaging
mvn -Dnot.cdh.release.build=false -Dmaven.repo.local=${HOME}/.m2/repository  install $DO_MAVEN_DEPLOY
cd ../..

# Build HCatalog
BUILD_OPTS="-Dversion=${FULL_VERSION} -Dforrest.home=$FORREST_HOME \
            -Dreactor.repo=file://${HOME}/.m2/repository           \
            -Dmvn.hadoop.profile=hadoop23"

cd hcatalog
ant $BUILD_OPTS src-release package "$@"

# If DO_MAVEN_DEPLOY == deploy, run the generate-maven-artifacts target
if [ "${DO_MAVEN_DEPLOY}" == "deploy" ]; then
    ant $BUILD_OPTS mvn-deploy "$@"
fi
