/usr/bin/sqoop
/usr/lib/sqoop/bin/sqoop.sh
/usr/lib/sqoop/cloudera/cdh_version.properties
/usr/lib/sqoop/sqoop-common-*.jar
/usr/lib/sqoop/sqoop-client-*.jar
/usr/lib/sqoop/lib/commons-cli-*.jar
/usr/lib/sqoop/lib/commons-lang-*.jar
/usr/lib/sqoop/lib/jansi-*.jar
/usr/lib/sqoop/lib/jersey-*.jar
/usr/lib/sqoop/lib/jline-*.jar
/usr/lib/sqoop/lib/json-simple-*.jar
/usr/lib/sqoop/lib/groovy-all-*.jar
/usr/lib/sqoop/lib/log4j-*.jar
/usr/lib/sqoop/lib/hamcrest-core-*.jar

