/usr/bin/sqoop2
/usr/lib/sqoop2/bin/sqoop.sh
/usr/lib/sqoop2/cloudera/cdh_version.properties
/usr/lib/sqoop2/sqoop-common-*.jar
/usr/lib/sqoop2/sqoop-client-*.jar
/usr/lib/sqoop2/lib/commons-cli-*.jar
/usr/lib/sqoop2/lib/commons-lang-*.jar
/usr/lib/sqoop2/lib/jansi-*.jar
/usr/lib/sqoop2/lib/jersey-*.jar
/usr/lib/sqoop2/lib/jline-*.jar
/usr/lib/sqoop2/lib/json-simple-*.jar
/usr/lib/sqoop2/lib/groovy-all-*.jar
/usr/lib/sqoop2/lib/log4j-*.jar
/usr/lib/sqoop2/lib/hamcrest-core-*.jar

