#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi

    if [ -z "${MAVEN_ONLY}" ]; then
        SITE_GOAL="site:site"
    fi
    
    mvn -DskipTests -Dcrunch.platform=2           \
    -Dslf4j.version=1.6.1                     \
    -Papache-release clean ${SITE_GOAL} source:jar-no-fork javadoc:jar $MAVEN_INST_DEPLOY "$@"

    if [ -z "${MAVEN_ONLY}" ]; then
        rm -rf build
        mkdir -p build/crunch-${FULL_VERSION}
        tar --strip-component=1 -C build/crunch-${FULL_VERSION} -xzvf crunch-dist/target/apache-crunch-*-bin.tar.gz
        cp -r target/site build/crunch-${FULL_VERSION}
        
        (cd build && tar -czf crunch-${FULL_VERSION}.tar.gz crunch-${FULL_VERSION})
    fi
else
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=crunch-${FULL_VERSION}/ --format=tar HEAD |gzip > build/crunch-${FULL_VERSION}.tar.gz
fi
