#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

TAR_NAME=hbase-solr-${FULL_VERSION}

if [ -z "$GIT_REPO" ]; then
    
# CDH_VERSIONS="-Dversion.solr=4.3.0-cdh4.2.0_search0.1.4-SNAPSHOT"
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi
    
    JAVA_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
        MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
        mvn clean -Pdist -Dhbase.api=0.96 -DskipTests $MAVEN_INST_DEPLOY $CDH_VERSIONS -Dmaven.repo.local=${HOME}/.m2/repository "$@"
    
# Creating a fake tarball
    rm -rf build
    mkdir -p build/${TAR_NAME}
    cp -r `ls -d * | grep -v build` build/${TAR_NAME}
    tar -C build -czf build/${TAR_NAME}.tar.gz ${TAR_NAME}
else
    git init
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=hbase-solr-${FULL_VERSION}/ --format=tar HEAD |gzip > build/hbase-solr-${FULL_VERSION}.tar.gz
fi
    
