#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi

    if [ -n "${MAVEN_ONLY}" ]; then
        MAVEN_DEPL=${MAVEN_INST_DEPLOY}
    fi

    MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
        mvn install -DskipTests ${MAVEN_DEPL} -fae "$@" 
    
    if [ -z "${MAVEN_ONLY}" ]; then
        MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" \
            mvn source:jar javadoc:javadoc -DskipTests -Psite ${MAVEN_INST_DEPLOY} "$@" 
        
        mkdir build
        tar -C build -xzvf flume-ng-dist/target/apache-flume-${FULL_VERSION}-bin.tar.gz
        tar -C build/apache-flume-${FULL_VERSION}-bin --strip-components=1 -xzvf flume-ng-dist/target/apache-flume-${FULL_VERSION}-bin.tar.gz
        tar -C build -czvf build/flume-ng-${FULL_VERSION}.tar.gz apache-flume-${FULL_VERSION}-bin
    fi
else
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=flume-ng-${FULL_VERSION}/ --format=tar HEAD |gzip > build/flume-ng-${FULL_VERSION}.tar.gz
fi
