#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

# FIXME: this needs to go away once we start using an actuall source tarball
[ -f pom.xml ] || cd src

if [ ! -d build/hadoop-${FULL_VERSION}/src ]; then
    mkdir -p build/hadoop-${FULL_VERSION}/src 
    tar --exclude='./build/*' -cf - . | (cd build/hadoop-${FULL_VERSION}/src ; tar xf -)
fi

if [ -z "$BUNDLE_SNAPPY" ] ; then
  [ -f /usr/lib/libsnappy.so ] && BUNDLE_SNAPPY="-Dsnappy.prefix=x -Dbundle.snappy=true -Dsnappy.lib=/usr/lib"
  [ -f /usr/lib64/libsnappy.so ] && BUNDLE_SNAPPY="-Dsnappy.prefix=x -Dbundle.snappy=true -Dsnappy.lib=/usr/lib64"
fi

# Build artifacts
MAVEN_SKIP_TESTS="-DskipTests -DskipTest -DskipITs"
JAVA_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" mvn $BUNDLE_SNAPPY -Pdist -Pnative -Psrc -Dtar ${MAVEN_SKIP_TESTS} install "$@" $DO_MAVEN_DEPLOY

# Build documentation
pushd hadoop-mapreduce-project/hadoop-yarn/hadoop-yarn-site
  JAVA_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" mvn site site:stage ${MAVEN_SKIP_TESTS} $@ || :
popd
JAVA_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" mvn site site:stage ${MAVEN_SKIP_TESTS} $@

# Rebuild and now mvn deploy the tarball - note the '-pl hadoop-dist' - if we chdir into hadoop-dist and build, it fails.
JAVA_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=256m" mvn -pl hadoop-dist -Pdist -Psrc -Dtar ${MAVEN_SKIP_TESTS} -Dmaven.deploy.skip=false install "$@" $DO_MAVEN_DEPLOY

(cd build/hadoop-${FULL_VERSION} ; tar --strip-components=1 -xzvf  ../../hadoop-dist/target/hadoop-${FULL_VERSION}.tar.gz)
# (cd build/hadoop-${FULL_VERSION}/src ; tar --strip-components=1 -xzvf  ../../../hadoop-dist/target/hadoop-${FULL_VERSION}-src.tar.gz)
(cd build/hadoop-${FULL_VERSION} ; cp -r ../../cloudera .)
(cd build && tar -czf hadoop-${FULL_VERSION}.tar.gz hadoop-${FULL_VERSION})

# Copy generated docs
mkdir -p build/share/doc/
cp -r target/site/* build/share/doc/

