#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

export LLVM_HOME=/opt/toolchain/llvm-3.3
export PATH=$LLVM_HOME/bin:$PATH
export IMPALA_HOME=`pwd`
export PIC_LIB_PATH=/opt/toolchain/impala_3rdparty-0.5
export BOOST_ROOT=/opt/toolchain/boost-pic-1.55.0
export DISABLE_CCACHE=1
export IMPALA_TOOLCHAIN=$IMPALA_HOME/toolchain/build
if [ -z "$GIT_REPO" ]; then
    IMPALA_TOOLCHAIN=$IMPALA_HOME/toolchain/build
    . $IMPALA_HOME/bin/impala-config.sh

    IMPALA_AUXTEST_HOME=Impala-auxiliary-tests
    IMPALA_AUXTEST_BRANCH=origin/master_sles12

    # Clone the client repo.
    [ -e "$IMPALA_AUXTEST_HOME" ] && rm -rf $IMPALA_AUXTEST_HOME
    (cd . && git clone git://github.mtv.cloudera.com/QE/Impala-auxiliary-tests.git)
    (cd ./Impala-auxiliary-tests && git checkout ${IMPALA_AUXTEST_BRANCH})

    echo ">>> Bootstrapping toolchain."
    pushd $IMPALA_AUXTEST_HOME
    $IMPALA_HOME/bin/impala-python jenkins/bootstrap_toolchain.py || { echo "toolchain bootstrap failed"; exit 1; }

    cd $IMPALA_HOME
    find $WORKSPACE -iname '*cmake*' -not -name CMakeLists.txt | grep -v -e cmake_module | grep -v -e thirdparty | xargs rm -Rf
    ./buildall.sh -noclean -skiptests -notests

    find $WORKSPACE -iname '*cmake*' -not -name CMakeLists.txt | grep -v -e cmake_module | grep -v -e thirdparty | xargs rm -Rf
    ./bin/make_release.sh -notests -build_static_libs
else
    rm -rf build impala-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build impala-${FULL_VERSION}
    cp -r $ALL_FILES impala-${FULL_VERSION}
    tar czf build/impala-${FULL_VERSION}.tar.gz impala-${FULL_VERSION}
fi
