#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. /mnt/toolchain/toolchain.sh
export LLVM_HOME=/opt/toolchain/llvm-3.3
export PATH=$LLVM_HOME/bin:$PATH
export IMPALA_HOME=`pwd`
export PIC_LIB_PATH=/opt/toolchain/impala_3rdparty-0.5

if [ -z "$TARBALL_ONLY" ]; then
    . $IMPALA_HOME/bin/impala-config.sh

    rm -f CMakeCache.txt
    ./buildall.sh -noclean -notestdata -skiptests -noformat
    rm -rf fe/target/dependency
    mvn -f fe/pom.xml dependency:copy-dependencies
    ./bin/make_release.sh -nopgo
fi


if [ -n "$TARBALL_ONLY" ]; then
    rm -rf build impala-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build impala-${FULL_VERSION}
    cp -r $ALL_FILES impala-${FULL_VERSION}
    tar czf build/impala-${FULL_VERSION}.tar.gz impala-${FULL_VERSION}
fi