#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

JAR_VERSION=1.1
BASE_URL=http://search.maven.org/remotecontent?filepath=com/github/fommil

if [ -z "$GIT_REPO" ]; then

    rm -rf build .build
    mkdir -p build/spark-netlib-${FULL_VERSION}/lib

    pushd  build/spark-netlib-${FULL_VERSION}/lib

#TODO: Try to move this into a pom.xml file and download via Maven.  I tried
#to do this but ran into problems downloading the native jar files
#See https://jira.cloudera.com/browse/CDH-29854
    wget $BASE_URL/jniloader/${JAR_VERSION}/jniloader-${JAR_VERSION}.jar -O jniloader-${JAR_VERSION}.jar
    wget $BASE_URL/netlib/netlib-native_system-linux-x86_64/${JAR_VERSION}/netlib-native_system-linux-x86_64-${JAR_VERSION}-natives.jar -O netlib-native_system-linux-x86_64-${JAR_VERSION}-natives.jar
    wget $BASE_URL/netlib/netlib-native_ref-linux-x86_64/${JAR_VERSION}/netlib-native_ref-linux-x86_64-${JAR_VERSION}-natives.jar -O netlib-native_ref-linux-x86_64-${JAR_VERSION}-natives.jar
    wget $BASE_URL/netlib/native_system-java/${JAR_VERSION}/native_system-java-${JAR_VERSION}.jar -O native_system-java-${JAR_VERSION}.jar
    wget $BASE_URL/netlib/native_ref-java/${JAR_VERSION}/native_ref-java-${JAR_VERSION}.jar -O native_ref-java-${JAR_VERSION}.jar 

    popd

    cp LICENSE.jniloader build/spark-netlib-${FULL_VERSION}/lib
    cp LICENSE.netlib-java build/spark-netlib-${FULL_VERSION}/lib
    cp LICENSE.openblas build/spark-netlib-${FULL_VERSION}/lib
    cp LICENSE.math-atlas build/spark-netlib-${FULL_VERSION}/lib

    tar -C build -czvf build/spark-netlib-${FULL_VERSION}.tar.gz spark-netlib-${FULL_VERSION}
else
    #We should never be coming here
    echo "Error - This component does not have an upstream tarball" >&2
    exit 1
fi
