#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    rm -rf build .build
    mkdir -p .build/bigtop-jsvc-${FULL_VERSION}
    cp -r * .build/bigtop-jsvc-${FULL_VERSION}
    mv .build build
    
    rm -f jsvc
    
    pushd unix
    ./configure --prefix=/usr
    make
    cp -f jsvc ../jsvc
    popd
    
    cp jsvc build/bigtop-jsvc-${FULL_VERSION}/jsvc
    tar -C build -czvf build/bigtop-jsvc-${FULL_VERSION}.tar.gz bigtop-jsvc-${FULL_VERSION}
else
    git init
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=bigtop-jsvc-${FULL_VERSION}/ --format=tar HEAD |gzip > build/bigtop-jsvc-${FULL_VERSION}.tar.gz
fi