#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    mvn -f maven/pom.xml clean install "$@"

    MAVEN_OPTIONS=$DO_MAVEN_DEPLOY make apps docs
    # Workaround for https://issues.cloudera.org/browse/HUE-1603
    rename .md .html docs/user-guide/*.md || :
    
# Make the entire tree relocatable
    bash tools/relocatable.sh

# Cloudera specific
    if [ -f Makefile.tarball ] ; then
        make prod
        rm -rf build/release/prod/hue-*.tgz build/release/prod/hue-${FULL_VERSION}
        mv build/release/prod/hue-* build/release/prod/hue-${FULL_VERSION}
        cp -r cloudera build/release/prod/hue-${FULL_VERSION}
        tar -C build/release/prod -czf build/hue-${FULL_VERSION}.tar.gz hue-${FULL_VERSION}
    fi
    
else
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=hue-${FULL_VERSION}/ --format=tar HEAD |gzip > build/hue-${FULL_VERSION}.tar.gz
fi
