#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    PROTOC_CDH5_PATH=/opt/toolchain/protobuf-2.5.0/bin/protoc

    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi

    THRIFT_HOME=/opt/toolchain/thrift-0.9.0
    export PATH=${THRIFT_HOME}/bin:${PATH}

    MAVEN_OPTS="-Xmx1536m -Xms256m -XX:MaxPermSize=256m" mvn source:jar-no-fork javadoc:jar $MAVEN_INST_DEPLOY -Dprotoc.executable=${PROTOC_CDH5_PATH} -DskipTests

    rm -rf build parquet-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build parquet-${FULL_VERSION}
    cp -r $ALL_FILES parquet-${FULL_VERSION}
    tar czf build/parquet-${FULL_VERSION}.tar.gz parquet-${FULL_VERSION}
else
    git init
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=parquet-${FULL_VERSION}/ --format=tar HEAD |gzip > build/parquet-${FULL_VERSION}.tar.gz
fi
