#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

ALL_FILES=`echo *`

mvn clean install -DskipTests $DO_MAVEN_DEPLOY -Dmaven.repo.local=${HOME}/.m2/repository "$@"

# Creating a fake tarball
rm -rf build
mkdir -p build/flume-ng-solr-${FULL_VERSION}
cp -r $ALL_FILES build/flume-ng-solr-${FULL_VERSION}
cp -f flume-indexer/target/flume-ng-solr-*.jar build/flume-ng-solr-${FULL_VERSION}
cp -f solr-mr/target/solr-mr*.jar build/flume-ng-solr-${FULL_VERSION}
cp -rf flume-indexer/target/lib build/flume-ng-solr-${FULL_VERSION}
tar -C build -czf build/flume-ng-solr-${FULL_VERSION}.tar.gz flume-ng-solr-${FULL_VERSION}
