#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

build_args="clean -DskipTests -Dhadoop.profile=23 source:jar install site javadoc:javadoc assembly:assembly $DO_MAVEN_DEPLOY -Dmaven.repo.local=${HOME}/.m2/repository"
security=true
if $security ; then
    build_args="$build_args -Psecurity"
fi
set -ex

mvn $build_args "$@"

mkdir -p build
for x in target/*.tar.gz ; do
  tar -C build -xzf $x
done
if $security ; then
    mv build/hbase-${FULL_VERSION}-security build/hbase-${FULL_VERSION}
fi
cp -r target/site/apidocs build/hbase-${FULL_VERSION}/docs
(cd build && tar --exclude='*/native/lib*' --exclude='*/lib/native/*' -czf hbase-${FULL_VERSION}.tar.gz hbase-${FULL_VERSION})
