#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi

    # This is here to make sure that we ignore any errors due to the circular dependency with Solr when
    # we are doing a maven-only build for version updating.
    if [ -n "${MAVEN_ONLY}" ]; then
        NEVER_FAIL=-fn
    fi
    
    mvn clean -DskipTests source:jar-no-fork javadoc:jar $MAVEN_INST_DEPLOY $NEVER_FAIL -Dmaven.repo.local=${HOME}/.m2/repository $@
    
    rm -rf build
    mkdir build
    cp sentry-dist/target/sentry-*-dist.tar.gz build/sentry-${FULL_VERSION}.tar.gz
else
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=sentry-${FULL_VERSION}/ --format=tar HEAD |gzip > build/sentry-${FULL_VERSION}.tar.gz
fi
