Document: hue-common
Title: Debian Hue Manual
Author: <insert document author here>
Abstract: This manual describes what Hue is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hue/hue.sgml.gz

Format: postscript
Files: /usr/share/doc/hue/hue.ps.gz

Format: text
Files: /usr/share/doc/hue/hue.text.gz

Format: HTML
Index: /usr/share/doc/hue/html/index.html
Files: /usr/share/doc/hue/html/*.html
