#!/bin/bash
# Copyright (c) 2009 Cloudera, inc
#
# Performs a release build

#
# Setup
#
set -ex
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}

IVY_EXTRA_ARGS="-Dmvnrepo=$IVY_MIRROR_PROP -Drepo.maven.org=$IVY_MIRROR_PROP"

if [ $(uname -m) != "x86_64" -a -z "$SKIP_EXTRA_NATIVE" ]; then
  echo Release build should be done on a 64-bit box to generate 1>&2
  echo both 64 and 32 bit native libraries. 1>&2
  exit 1
fi

JAVA32_HOME=${JAVA32_HOME:-$JAVA_HOME}
JAVA64_HOME=${JAVA64_HOME:-$JAVA_HOME}

# Do the build
BIN_DIR=$(readlink -f $(dirname $0))
RELEASE_DIR=$BIN_DIR/..

RELEASE_DIR=$PWD

failIfNotOK() {
  if [ $? != 0 ]; then
    echo "Failed!"
    exit $?
  fi
}

# Clean build directory
#
BUILDDIR=${RELEASE_DIR}/build
rm -rf ${BUILDDIR}
failIfNotOK
mkdir ${BUILDDIR}
failIfNotOK

#
# Building Hadoop
#
cd $RELEASE_DIR

if [ -z "$SKIP_EXTRA_NATIVE" ]; then
JAVA_HOME=$JAVA32_HOME \
  CFLAGS=-m32 \
  CXXFLAGS=-m32 \
  ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Dforrest.home=$FORREST_HOME \
  -Dcompile.native=true -Dcompile.c++=true \
  -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
  -propertyfile cloudera/build.properties \
  ${IVY_EXTRA_ARGS} \
  task-controller package-native

JAVA_HOME=$JAVA64_HOME
fi

if [ -z "$SKIP_JDIFF" ]; then
ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Djdiff.stable=0.20.1 \
  -Djdiff.build.dir=build/docs/jdiff-cloudera \
  -propertyfile build.properties \
  ${IVY_EXTRA_ARGS} \
  -propertyfile cloudera/build.properties api-report
fi

# Copy them into the main build directory to be included in the tarball
mkdir -p build/hadoop-$FULL_VERSION/docs/

ant \
  -Dreactor.repo=file://$HOME/.m2/repository \
  -Dforrest.home=$FORREST_HOME \
  -Dcompile.native=true -Dcompile.c++=true \
  -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
  -propertyfile cloudera/build.properties \
  ${IVY_EXTRA_ARGS} \
  compile-c++ compile-c++-examples task-controller tar

cp build/hadoop-$FULL_VERSION.tar.gz build/mr1-$FULL_VERSION.tar.gz

# Create a manifest for the hadoop-0.20-client
(cd cloudera/maven-packaging/hadoop-client ; mvn assembly:single)
(cd cloudera/maven-packaging/hadoop-client/target/hadoop-client*/client ; ls) > build/hadoop-$FULL_VERSION/hadoop-client.list

if [ -z "$SKIP_MVN_EXPLICIT" ]; then
# Change to cloudera/maven directory, and install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
cd cloudera/maven-packaging
mvn -Dnot.cdh.release.build=false install $DO_MAVEN_DEPLOY
fi
