#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -ex

if [ -z ${THRIFT_HOME} ] ; then
  echo "THRIFT_HOME not set"
  exit 1
fi

if [ ! -f "${THRIFT_HOME}/bin/thrift" ] ; then
  echo "Thrift compiler not found at : ${THRIFT_HOME}/bin"
  exit 1
fi

# Add -Pfull-build to include documentation build
mvn clean \
	source:jar \
	install \
	javadoc:javadoc \
        -Phadoop-0.23 \
        -Dhadoop.profile=23 \
	-Dbuild.revision=${FLUME_BUILD_REF} \
	-Dthrift.executable=${THRIFT_HOME}/bin/thrift \
	-DskipTests \
	-Pfull-build \
	-Dmaven.repo.local=${HOME}/.m2/repository \
	${DO_MAVEN_DEPLOY}

mkdir build
cp flume-distribution/target/flume-distribution-${FULL_VERSION}-project.tar.gz build/flume-${FULL_VERSION}.tar.gz
