#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

# This Boost deployment is special: even the static archives were compiled
# with -fPIC. That makes it necessary for the client build
export BOOST_ROOT=${BOOST_ROOT:-/opt/toolchain/boost-pic-1.55.0}

if [ -z "$GIT_REPO" ]; then
    # We're building.

    # ./thirdparty/build-if-necessary.sh does not work outside of a git
    # repo, so we always rebuild thirdparty. It's unfortunate, but the only
    # side effect is a slower build.
    #
    # TODO: Convert to Cloudera Toolchain.
    ./thirdparty/download-thirdparty.sh
    ./thirdparty/build-thirdparty.sh

    export NO_REBUILD_THIRDPARTY=1
    CMAKE='thirdparty/installed/bin/cmake -DKUDU_LINK=static'
    MAKE='make -j8'
    for type in release fastdebug; do
        rm -rf CMakeCache.txt CMakeFiles/
        ${CMAKE} -DCMAKE_BUILD_TYPE=${type} -DNO_TESTS=1 .
        ${MAKE}

        rm -rf CMakeCache.txt CMakeFiles/
        ${CMAKE} -DCMAKE_BUILD_TYPE=${type} -DKUDU_EXPORTED_CLIENT=1 -DNO_TESTS=1 .
        ${MAKE} install DESTDIR=`pwd`/client-${type}
    done

else
    # We're packaging up the source code to be built.
    rm -rf build kudu-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build kudu-${FULL_VERSION}
    cp -r $ALL_FILES kudu-${FULL_VERSION}
    tar czf build/kudu-${FULL_VERSION}.tar.gz kudu-${FULL_VERSION}
fi

