#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}
BUILD_OPTS="-Divy.home=${HOME}/.ivy2 -Dmvnrepo=$IVY_MIRROR_PROP -Divy_install_path=${HOME}/.ant/lib -lib ${HOME}/.ant/lib"

# FIXME: this needs to be fixed at the product level
ant $BUILD_OPTS ivy-bootstrap
mkdir solr/test-framework/lib || :

# FIXME: At some point we'd have to make sure that the locally built
# lucene artifacts get built and used by a build of Solr
# (cd lucene ; ant $BUILD_OPTS clean package-all-binary)

# Build Solr itself
(cd solr ; ant $BUILD_OPTS clean package-local-src-tgz create-package "$@")

# Putting the build artifact in place
rm -rf build
mkdir build
pushd build
  tar -xzf ../solr/build/apache-solr-*-src.tgz
  tar -C apache-solr-* --strip-components=1 -xzf ../solr/package/apache-solr-*.tgz
  # FIXME: the following needs to be FULL_VERSION by default
  mv apache-solr-* solr-${FULL_VERSION}
  tar -czf solr-${FULL_VERSION}.tar.gz solr-${FULL_VERSION}
popd

# Change to cloudera/maven directory, and install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
# cd cloudera/maven-packaging
# mvn -Dnot.cdh.release.build=false install -Dmaven.repo.local=${HOME}/.m2/repository $DO_MAVEN_DEPLOY
