#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi
    mvn -DskipTests -s settings.xml -Pdev clean  package   -U
    rm -rf build
    mkdir build
	cp target/keytrusteekp-*.jar build
    cp target/keytrusteekp-*.tar.gz build/keytrustee-keyprovider-${FULL_VERSION}.tar.gz
else
    #For keytrustee-keyprovider there are no pristine tarballs etc. so we
    #have to just generate a tarball for the source and copy it to 
    #./build
    #This code is basically copied from the do-component-build file
    #for impala
    rm -rf build keytrustee-keyprovider-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build keytrustee-keyprovider-${FULL_VERSION}
    cp -r $ALL_FILES keytrustee-keyprovider-${FULL_VERSION}
    tar czf build/keytrustee-keyprovider-${FULL_VERSION}.tar.gz keytrustee-keyprovider-${FULL_VERSION}
fi
