#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}
BUILD_OPTS="-Dversion=${FULL_VERSION} -Dforrest.home=$FORREST_HOME -D_vtype= \
            -Divy.home=${HOME}/.ivy2 -Drepo.maven.org=$IVY_MIRROR_PROP       \
            -Dreactor.repo=file://${HOME}/.m2/repository"


ant $BUILD_OPTS src-release tar "$@"

rm -rf build/hcatalog-${FULL_VERSION}*
mkdir build/hcatalog-${FULL_VERSION}
for i in build/*.tar.gz ; do
  tar -C build/hcatalog-${FULL_VERSION} --strip-components=1 -xzf $i
done
(cd build ; tar czf hcatalog-${FULL_VERSION}.tar.gz hcatalog-${FULL_VERSION})
