#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    if [ -z "${DO_MAVEN_DEPLOY}" ]; then
        MAVEN_INST_DEPLOY=install
    else
        MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
    fi

    export THRIFT_HOME=/opt/toolchain/thrift-0.9.0
    export PATH=${THRIFT_HOME}/bin:${PATH}
    
    mvn $MAVEN_INST_DEPLOY -Pdist -DskipTests
    
    rm -rf build llama-${FULL_VERSION}
    ALL_FILES=`echo *`
    mkdir build llama-${FULL_VERSION}
    cp -r $ALL_FILES llama-${FULL_VERSION}
    tar czf build/llama-${FULL_VERSION}.tar.gz llama-${FULL_VERSION}
else
    git init
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=llama-${FULL_VERSION}/ --format=tar HEAD |gzip > build/llama-${FULL_VERSION}.tar.gz
fi

