#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ -z "$GIT_REPO" ]; then
    # In Bigtop, CATALINA_BASE always differs from CATALINA_HOME,
    # but if you don't set BASE it assumes it's the same as HOME.
    SET_CATALINA_HOME='  -Dcatalina.home="$CATALINA_HOME" \\'
    SET_CATALINA_BASE='  -Dcatalina.base="$CATALINA_BASE" \\'
    for tool_wrapper in `find ./ -name tool-wrapper.sh`; do
        sed -i -e "s#${SET_CATALINA_HOME}#${SET_CATALINA_HOME}\n${SET_CATALINA_BASE}#" ${tool_wrapper}
    done

    rm -rf build .build
    mkdir -p .build/bigtop-tomcat-${FULL_VERSION}
    cp -r * .build/bigtop-tomcat-${FULL_VERSION}
    mv .build build
    
    rm -rf dl
    mkdir dl
    # ant -Dbase.path=dl clean download -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar -Dnsis.loc=http://archive.cloudera.com/tarballs/nsis-2.46.zip
    ant -v -Dbase-apache.loc.1=http://mirror.infra.cloudera.com/apache/ -Dbase-apache.loc.2=http://mirror.infra.cloudera.com/apache/ -Dbase.path=dl clean download -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar -Dnsis.loc=http://archive.cloudera.com/tarballs/nsis-2.46.zip
    #ant -Dbase.path=dl -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar
    ant -v -Dbase-apache.loc.1=http://mirror.infra.cloudera.com/apache/ -Dbase-apache.loc.2=http://mirror.infra.cloudera.com/apache/ -Dbase.path=dl -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar
    #ant -Dbase.path=dl -Dskip.installer=true -f dist.xml dist-static package-tgz -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar
    ant -v -Dbase-apache.loc.1=http://mirror.infra.cloudera.com/apache/ -Dbase-apache.loc.2=http://mirror.infra.cloudera.com/apache/ -Dbase.path=dl -Dskip.installer=true -f dist.xml dist-static package-tgz -Djdt.loc.1=http://archive.cloudera.com/tarballs/ecj-3.7.jar
    
    tar -C build --strip-components=1 -xzf output/release/v*/bin/apache-tomcat-*[0-9].tar.gz
    
    tar -C build/bigtop-tomcat-${FULL_VERSION} --strip-components=1 -xzf output/release/v*/bin/apache-tomcat-*[0-9].tar.gz
    tar -C build -czvf build/bigtop-tomcat-${FULL_VERSION}.tar.gz bigtop-tomcat-${FULL_VERSION}
else
    git init
    git add .
    git commit -a -m "Temporary commit for tarball"
    mkdir -p build
    git archive --prefix=bigtop-tomcat-${FULL_VERSION}/ --format=tar HEAD |gzip > build/bigtop-tomcat-${FULL_VERSION}.tar.gz
fi
